spring:

  datasource:
    url: jdbc:mysql://localhost:3306/vulsmanager?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  #每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #邮箱配置
  mail:
    host:
    username:
    #邮箱的授权码
    password:
    default-encoding: UTF-8